# Generated by Django 4.2.4 on 2023-11-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='products',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
