# Generated by Django 4.2.4 on 2023-11-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='married',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
